services:
  - type: web
    name: multi-maze
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_REDIRECT_URI
        sync: false
      - key: AUTH_SESSION_SECRET
        generateValue: true
