create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  event_type text not null check (event_type ~ '^[a-z0-9_]{2,40}$'),
  session_hash text null,
  properties jsonb not null default '{}'::jsonb
);

create index if not exists analytics_events_created_at_idx
  on public.analytics_events (created_at desc);

create index if not exists analytics_events_type_idx
  on public.analytics_events (event_type, created_at desc);

comment on table public.analytics_events is
  'Pseudonymised analytics events for A Maze Inc. No raw IP address, email or Discord identifier is stored here.';

alter table public.analytics_events disable row level security;
